jobs:
  test-on-ubuntu:
    name: Run zip4j tests on ubuntu
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B clean verify --file pom.xml
  test-on-windows:
    if: ${{ false }}
    name: Run zip4j tests on Windows
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B -Pskip-slow-tests clean verify --file pom.xml
name: Verify Build
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
